name: "ledfx"

services:
  ledfx:
    image: ghcr.io/ledfx/ledfx:latest
    container_name: ledfx
    network_mode: host
    restart: always
    volumes:
      - config:/home/ledfx/ledfx-config

volumes:
  config:
